# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4edc055957d075bc504eec594a6917ee95a9f0c139546c002b3e80c485a170d9e2de5e5b2623fd1683fd468dfdf3e13932770ebd8cc951a5b76db190a60bccb2

test:
  secret_key_base: a03a1e26393f4f3aae8f7ea0b6a9ce3006c5923376fd9ca6b83c987401a3137312f593f8ca9b2bb989d62c57d4e86cf55b3c750b01b16328aa3ff21283950871

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
